# -*- coding: utf-8 -*-
"""FeatExtract_Segment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fw4gvJ_elGPbG4sZnxoYqUlGPoNf_Xbt
"""

from google.colab import drive
drive.mount('/content/gdrive')

import numpy as np
import cv2 
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import scipy
import os
os.chdir('/content/gdrive/My Drive/MP2/')

#Read Images
img1 = cv2.imread('benign_4x/_11064.tif')
img2 = cv2.imread('benign_4x/_11016.tif')
img3 = cv2.imread('benign_4x/_11001.tif')
img_gt1 = cv2.imread('benign_4x/_11064_gt.png')
img_gt2 = cv2.imread('benign_4x/_11016_gt.png')
img_gt3 = cv2.imread('benign_4x/_11001_gt.png')
img_gt1 = np.array(img_gt1)
img_gt2 = np.array(img_gt2)
img_gt3 = np.array(img_gt3)

#Image1
lab1= cv2.cvtColor(img1, cv2.COLOR_BGR2LAB)
plt.imshow(lab1)
plt.show()

l1, a1, b1 = cv2.split(lab1)
plt.imshow(l1, cmap ='gray')
plt.show()
plt.imshow(a1, cmap= 'gray')
plt.show()
plt.imshow( b1, cmap = 'gray')
plt.show()

labm1 = cv2.medianBlur(lab1, 9)
plt.imshow(labm1)
plt.show()

#Image2
lab2= cv2.cvtColor(img2, cv2.COLOR_BGR2LAB)
plt.imshow(lab2)
plt.show()

l2, a2, b2 = cv2.split(lab2)
plt.imshow(l2, cmap ='gray')
plt.show()
plt.imshow(a2, cmap= 'gray')
plt.show()
plt.imshow( b2, cmap = 'gray')
plt.show()

labm2 = cv2.medianBlur(lab2, 9)
plt.imshow(labm2)
plt.show()

#Image 3
lab3= cv2.cvtColor(img3, cv2.COLOR_BGR2LAB)
plt.imshow(lab3)
plt.show()

l3, a3, b3 = cv2.split(lab3)
plt.imshow(l3, cmap ='gray')
plt.show()
plt.imshow(a3, cmap= 'gray')
plt.show()
plt.imshow( b3, cmap = 'gray')
plt.show()

labm3 = cv2.medianBlur(lab3, 9)
plt.imshow(labm3)
plt.show()

plt.imshow(lab3[:,:,1])
plt.show()

#Extract Gabor Features

ksize = 9  # Size of Gabor kernel
theta = 0.0 
gamma = 1
sigma = 1
#converting to grayscale
#img_gray= cv2.cvtColor(img2_clean, cv2.COLOR_BGR2GRAY)
kernels = []
features = []
i = 0
for sigma in np.arange(1,1.2,0.5):
  for lamda in np.arange(3.25,4.1,0.25):
    for gamma in np.arange(0.5,1.25,0.25):
      k = cv2.getGaborKernel((ksize, ksize), sigma, theta, lamda, gamma, 0, ktype=cv2.CV_32F)   
      kernels.append(k) 
      fimg = cv2.filter2D(lab3, cv2.CV_8UC1, k)
      #fimg = cv2.GaussianBlur(fimg, (15,15), 5, 5)
      fimg = cv2.medianBlur(fimg, 5)
      #plt.imshow(fimg)
      #plt.show()
      plt.figure(figsize = (8,8))
      plt.imshow(fimg)
      plt.show()
      print(ksize, lamda, gamma, i)
      i = i+1
      #fimg = fimg.reshape((fimg.shape[0]*fimg.shape[1],))
      #features.append(fimg)
      #ColourImage
      #fimg = cv2.filter2D(imgHSV[:,:,2], cv2.CV_8UC1, k)
      #fimg = cv2.GaussianBlur(fimg, (15,15), 5, 5)
      #fimg = cv2.medianBlur(fimg, 11)

      fimg = fimg.reshape((fimg.shape[0]*fimg.shape[1],3))
      features.append(fimg[:,0])
      features.append(fimg[:,1])
      features.append(fimg[:,2])

features3 = np.array(features)
features3 = features3.T
kernels = np.array(kernels)

features3 = np.hstack((features3,labm3[:,:,0].reshape((img1.shape[0]*img1.shape[1]),1)))
features3 = np.hstack((features3, labm3[:,:,1].reshape((img1.shape[0]*img1.shape[1]),1)))
features3 = np.hstack((features3,labm3[:,:,2].reshape((img1.shape[0]*img1.shape[1]),1)))

#K Means Clustering
kmeans = KMeans(n_clusters=3, init = 'k-means++')
kmeans.fit(features3)
y = kmeans.predict(features3)
img_seg3 = y.reshape((img1.shape[0], img1.shape[1]))
img_seg_copy3 = np.copy(img_seg3)



transF3 = kmeans.transform(features3)
dist = transF3[:,2]
dist[y!=2] = 0
plt.hist(dist[dist!=0], 200)
plt.xlim([0,250])
#plt.plot(dist)
plt.show()

#dist[dist  60] = 0
ind_change = np.where(dist != 0)[0]
img_check = np.zeros(dist.shape)
listimg = lab3[:,:,1].reshape(lab3[:,:,1].shape[0]* lab3[:,:,1].shape[1],)
print(listimg.shape)
img_check[ind_change] = 255
img_check = img_check.reshape(img3.shape[0],img3.shape[1])
img_see = np.copy(lab3)
img_see[img_check == 0] = 0  
plt.figure(figsize = (20,20))
plt.imshow(img_see, cmap = 'gray')
plt.show()



plt.figure(figsize = (20,20))
plt.imshow(img_seg3==1, cmap = 'gray')
plt.show()

img_seg1 = cv2.medianBlur(np.uint8(img_seg1), 9)
img_seg2 = cv2.medianBlur(np.uint8(img_seg2), 9)
img_seg3 = cv2.medianBlur(np.uint8(img_seg3), 9)

#Plotting Segmented Image

fig, (a1,a2,a3) = plt.subplots(1,3, figsize=(30,30))
a1.imshow(img1, cmap = 'gray')
a2.imshow(img_gt1 , cmap = 'gray')
a3.imshow(img_seg1 == cell1, cmap = 'gray')
fig.show()

fig, (a1,a2,a3) = plt.subplots(1,3, figsize=(30,30))
a1.imshow(img2, cmap = 'gray')
a2.imshow(img_gt2 , cmap = 'gray')
a3.imshow(img_seg2 == cell2, cmap = 'gray')
fig.show()

fig, (a1,a2,a3) = plt.subplots(1,3, figsize=(30,30))
a1.imshow(img3, cmap = 'gray')
a2.imshow(img_gt3 , cmap = 'gray')
a3.imshow(img_seg3 == cell3, cmap = 'gray')
fig.show()

counts = np.bincount(img_seg2.flatten())

#Find Background Class - most populated class
counts = np.bincount(img_seg1.flatten())
background1 = np.argmax(counts)
if(background1):
  print("Changing 1")
  img_seg1[img_seg1 == background1] = 255
  img_seg1[img_seg1 == 0] = background1
  img_seg1[img_seg1 == 255] = 0

counts = np.bincount(img_seg2.flatten())
background2 = np.argmax(counts)
if(background2):
  print("Changing 2")
  img_seg2[img_seg2 == background2] = 255
  img_seg2[img_seg2 == 0] = background2
  img_seg2[img_seg2 == 255] = 0

counts = np.bincount(img_seg3.flatten())
background3 = np.argmax(counts)
if(background3):
  print("Changing 3")
  img_seg3[img_seg3 == background3] = 255
  img_seg3[img_seg3 == 0] = background3
  img_seg3[img_seg3 == 255] = 0

#Finding Cell and Cytoplasm Clusters
#Img1
clusters = np.unique(img_seg1)
clusters = clusters[1:]
mask1 = np.zeros(img_seg1.shape)
mask2 = np.zeros(img_seg1.shape)
mask1[img_seg1 == clusters[0]] = 255
mask2[img_seg1 == clusters[1]] = 255

hist1 = cv2.calcHist([lab1],[1],np.uint8(mask1),[255],[0,256])
peak1 = np.argsort(-hist1.flatten())[0]
hist2 = cv2.calcHist([lab1],[1],np.uint8(mask2),[255],[0,256])
peak2 = np.argsort(-hist2.flatten())[0]

if(peak1 > peak2):
  cell1 = clusters[0]
  cyto1 = clusters[1]
else:
  cell1 = clusters[1]
  cyto1 = clusters[0]

#img2
clusters = np.unique(img_seg2)
clusters = clusters[1:]
mask1 = np.zeros(img_seg2.shape)
mask2 = np.zeros(img_seg2.shape)
mask1[img_seg2 == clusters[0]] = 255
mask2[img_seg2 == clusters[1]] = 255

hist1 = cv2.calcHist([lab2],[1],np.uint8(mask1),[255],[0,256])
peak1 = np.argsort(-hist1.flatten())[0]
hist2 = cv2.calcHist([lab2],[1],np.uint8(mask2),[255],[0,256])
peak2 = np.argsort(-hist2.flatten())[0]

if(peak1 > peak2):
  cell2 = clusters[0]
  cyto2 = clusters[1]
else:
  cell2 = clusters[1]
  cyto2 = clusters[0]

#Img3
clusters = np.unique(img_seg3)
clusters = clusters[1:]
mask1 = np.zeros(img_seg3.shape)
mask2 = np.zeros(img_seg3.shape)
mask1[img_seg3 == clusters[0]] = 255
mask2[img_seg3 == clusters[1]] = 255

hist1 = cv2.calcHist([lab3],[1],np.uint8(mask1),[255],[0,256])
peak1 = np.argsort(-hist1.flatten())[0]
hist2 = cv2.calcHist([lab3],[1],np.uint8(mask2),[255],[0,256])
peak2 = np.argsort(-hist2.flatten())[0]

if(peak1 > peak2):
  cell3 = clusters[0]
  cyto3 = clusters[1]
else:
  cell3 = clusters[1]
  cyto3 = clusters[0]

def find_tumors(img, cell, cyto, background):
  contours, heirarchy = cv2.findContours(np.uint8(img), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
  n = len(contours)
  areas = []
  for cnt in contours:
    area = cv2.contourArea(cnt)
    areas.append(area)

  areas = np.array(areas)
  ind = np.argsort(-1*areas)
  thresh = np.mean(areas) + np.std(areas)
  z = np.zeros(img_seg1.shape)
  tumor = []
  check = 0

  for i in np.arange(0,n,1):
    z = np.zeros(img.shape)
    if(areas[i]>=thresh):
      cv2.drawContours(z,contours[i], -1,(255,255,255), 3 )
      masked_image = scipy.ndimage.morphology.binary_fill_holes(z)
      z[masked_image] = img[masked_image]
      counts = np.bincount(img_seg2.flatten())
      if(counts[cell] >= counts[cyto]):
        tumor.append(i)
        img[masked_image] = cell
      else:
        img[z == cyto] = background
        check = 1

  imgr = np.copy(img) 
  if(check):
    print("again")
    imgr = find_tumors(img, cell, cyto, background)

  return imgr

img_seg3_copy = np.copy(img_seg3)
imgr3 = find_tumors(img_seg3_copy, cell3, cyto3, background3)
fig, (p1,p2) = plt.subplots(1,2,figsize = (20,20))
p1.imshow(imgr3, cmap = 'gray')
p2.imshow(img_gt3)
plt.show()

#Find Contours
contours1, heirarchy = cv2.findContours(np.uint8(img_seg1), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

#Finding top n contours with maximum areas
n = len(contours1)
areas = []

for cnt in contours1:
  area = cv2.contourArea(cnt)
  areas.append(area)

areas = np.array(areas)
ind = np.argsort(-1*areas)


z = np.zeros(img_seg1.shape)
thresh = np.mean(areas)+np.std(areas)
for i in np.arange(0,n,1):
  if(areas[i]>=0):
    cv2.drawContours(z,contours1[i], -1,(255,255,255), 3 )

plt.imshow(z, cmap = 'gray')
plt.show()
print(thresh)

masked_image = scipy.ndimage.morphology.binary_fill_holes(z)
plt.imshow(masked_image, cmap = 'gray')
plt.show()
print(np.unique(masked_image))

areas1 = areas

z1 = (areas1 - np.mean(areas1))/np.std(areas1)
plt.plot(z1[np.argsort(-z1)], 'o-r')
plt.xlim([-5,100])
plt.show()

z2 = (areas2 - np.mean(areas2))/np.std(areas2)
plt.plot(z2[np.argsort(-z2)], 'o-r')
plt.xlim([-5,100])
plt.show()

z3 = (areas3 - np.mean(areas3))/np.std(areas3)
plt.plot(z3[np.argsort(-z3)], 'o-r')
plt.xlim([-5,100])
plt.show()



"""HISTOGRAM"""

color = ('b','g','r')
for i,col in enumerate(color):
    histr = cv2.calcHist([lab3],[i],np.uint8(mask1),[255],[0,256])
    plt.plot(histr,color = col)
    plt.xlim([0,255])
    print(i)
plt.show()

hist = cv2.calcHist([lab1],[1],np.uint8(mask2),[255],[0,256])
plt.plot(hist)
plt.xlim([0,255])
plt.show()
#a = np.correlate(hist.flatten(), hist.flatten(), mode = 'full')
print(np.argsort(-hist.flatten()))

plt.imshow(lab3[:,:,1], cmap = 'gray')
plt.show()

"""PCA"""

from sklearn.decomposition import PCA

pca = PCA(n_components = 10)
pca.fit(features.T)
X = pca.components_
var = pca.explained_variance_
print(var)
Xt = X.T

fig, (a1,a2,a3,a4) = plt.subplots(1,4,figsize = (25,25))
a1.imshow(X[0].reshape(1440,1920), cmap = 'gray')
a2.imshow(X[1].reshape(1440,1920), cmap = 'gray')
a3.imshow(X[2].reshape(1440,1920), cmap = 'gray')
a4.imshow(X[3].reshape(1440,1920), cmap = 'gray')
fig.show()

"""ANALYSIS"""

mask = img_seg !=2
view = np.copy(lab)
view[mask] = 0
plt.figure(figsize = (15,15))
plt.imshow(view[:,:,0], cmap = 'gray')
plt.show()

masinv = img_seg != 2
mask1 = np.copy(justlab1)
mask1[masinv] = 0
mask1[img_seg == 2] = 255
plt.figure(figsize = (15,15))
#plt.imshow(mask1, cmap = 'gray')
hist = cv2.calcHist([view],[0], np.uint8(mask1), [256], [0,256] )
plt.plot(hist)
plt.show()

plt.figure(figsize = (15,15))
plt.hist(areas,len(areas))
plt.show()
print(np.mean(areas) + np.std(areas))

#Labelling the image

(labels, counts) = np.unique(img_seg[masked_image], return_counts= True)
cellClusterLabel = labels[np.argmax(counts)]
print(cellClusterLabel)
masked_img_inv = masked_image == False
backgroundMask = (img_seg == 0)
isolatedMask = ((img_seg *masked_img_inv) == 2).astype(int)
isolatedMask[masked_image] = 2

isolatedMask[backgroundMask] = 0

img_gt_gray = cv2.cvtColor(img_gt, cv2.COLOR_BGR2GRAY)

#Plotting correctly labelled Segmented Image
fig, (a1,a2,a3) = plt.subplots(1,3, figsize=(25,25))
a1.imshow(img)
a2.imshow(img_gt_gray, cmap = 'gray')
a3.imshow(isolatedMask, cmap = 'gray')
fig.show

#Calculate dice score
num_clusters = 4
gray_values=[]
img_shape = img_gt_gray.shape
img_gt_gray.reshape(img_shape[0]*img_shape[1])
isolatedMask.reshape(img_shape[0]*img_shape[1])
for i in range(num_clusters-1):
  gray_values.append(int(np.mean(img_gt_gray[(img_gt_gray>=255*i/4) & (img_gt_gray<255*(i+1)/4)])))
gray_values.append(255)
print(gray_values)
for i in range(num_clusters):
  img_gt_gray[img_gt_gray==gray_values[i]]=i

gt_pixel_ratios=[]
seg_pixel_ratios=[]
for i in range(num_clusters):
  seg_pixel_ratios.append(np.sum(isolatedMask[isolatedMask==i]==i))
  gt_pixel_ratios.append(np.sum(img_gt_gray[img_gt_gray==i]==i))

print(seg_pixel_ratios)
print(gt_pixel_ratios)

seg_order = np.argsort(seg_pixel_ratios)
print(seg_order)

gt_order = np.argsort(gt_pixel_ratios)
print(gt_order)

for i in range(num_clusters):
  isolatedMask[isolatedMask==seg_order[i]]= -gt_order[i]
for i in range(num_clusters):
  isolatedMask[isolatedMask==(-i)]= i 
isolatedMask.reshape((img_shape[0],img_shape[1]))
plt.imshow(isolatedMask,cmap='gray')

img_gt_gray.reshape((img_shape[0],img_shape[1]))

dice = []
for k in range(num_clusters):
  dice.append(np.sum(isolatedMask[img_gt_gray==k]==k)*2.0 / (np.sum(isolatedMask[isolatedMask==k]==k) + np.sum(img_gt_gray[img_gt_gray==k]==k)))
print(dice)

#Benign - 4x - 011
#img11 = np.copy(img)
#img_gt_gray11 = np.copy(img_gt_gray)
#isolatedMask11 = np.copy(isolatedMask)
#img_seg11 = np.copy(img_seg)
img11 = cv2.imread('benign_4x/_11001.tif')
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img11)
a2.imshow(img_gt_gray11, cmap = 'gray')
a3.imshow(isolatedMask11, cmap = 'gray')
a4.imshow(img_seg11)
fig.show
fig.savefig('b_011.png')

#Benign - 4x - 016
#img16 = np.copy(img)
#img_gt_gray16 = np.copy(img_gt_gray)
#isolatedMask16 = np.copy(isolatedMask)
#img_seg16 = np.copy(img_seg)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img16)
a2.imshow(img_gt_gray16, cmap = 'gray')
a3.imshow(isolatedMask16, cmap = 'gray')
a4.imshow(img_seg16)
fig.show
fig.savefig('b_016.png')

#Benign - 4x - 064
#img64 = np.copy(img)
#img_gt_gray64 = np.copy(img_gt_gray)
#isolatedMask64 = np.copy(isolatedMask)
#img_seg64 = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img64)
a2.imshow(img_gt_gray64, cmap = 'gray')
a3.imshow(isolatedMask64, cmap = 'gray')
a4.imshow(img_seg64)
fig.show
fig.savefig('b_064.png')

#Malignant - 4x - 017
img17m = np.copy(img)
img_gt_gray17m = np.copy(img_gt_gray)
isolatedMask17m = np.copy(isolatedMask)
img_seg17m = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img17m)
a2.imshow(img_gt_gray17m, cmap = 'gray')
a3.imshow(isolatedMask17m, cmap = 'gray')
a4.imshow(img_seg17m)
fig.show
fig.savefig('m_017.png')

#Malignant - 4x - 018
img18m = np.copy(img)
img_gt_gray18m = np.copy(img_gt_gray)
isolatedMask18m = np.copy(isolatedMask)
img_seg18m = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img18m)
a2.imshow(img_gt_gray18m, cmap = 'gray')
a3.imshow(isolatedMask18m, cmap = 'gray')
a4.imshow(img_seg18m)
fig.show
fig.savefig('m_018.png')

#Malignant - 4x - 020
img20m = np.copy(img)
img_gt_gray20m = np.copy(img_gt_gray)
isolatedMask20m = np.copy(isolatedMask)
img_seg20m = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img20m)
a2.imshow(img_gt_gray20m, cmap = 'gray')
a3.imshow(isolatedMask20m, cmap = 'gray')
a4.imshow(img_seg20m)
fig.show
fig.savefig('m_020.png')

img1gnb = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img1g = cv2.GaussianBlur(img1gnb, (15,15), 5, 5)
val = np.ceil(np.mean(img1g) - np.std(img1g))
ret,imgthresh1 = cv2.threshold(img1g,val,255,cv2.THRESH_BINARY)
mask1 = imgthresh1 == 255
img1_clean = np.copy(img1)
img1_clean[mask1] = 255

img2gnb = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
img2g = cv2.GaussianBlur(img2gnb, (15,15), 5, 5)
val = np.ceil(np.mean(img2g) - np.std(img2g))
ret,imgthresh2 = cv2.threshold(img2g,val,255,cv2.THRESH_BINARY)
mask2 = imgthresh2 == 255
img2_clean = np.copy(img2)
img2_clean[mask2] = 255

img3gnb = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
img3g = cv2.GaussianBlur(img3gnb, (15,15), 5, 5)
val = np.ceil(np.mean(img3g) - np.std(img3g))
ret,imgthresh3 = cv2.threshold(img3g,val,255,cv2.THRESH_BINARY)
mask3 = imgthresh3 == 255
img3_clean = np.copy(img3)
img3_clean[mask3] = 255


###

lab= cv2.cvtColor(img3, cv2.COLOR_BGR2LAB)
plt.imshow(lab)
plt.show()

#-----Splitting the LAB image to different channels-------------------------
l, a, b = cv2.split(lab)
plt.imshow(l, cmap ='gray')
plt.show()
plt.imshow(a, cmap= 'gray')
plt.show()
plt.imshow( b, cmap = 'gray')
plt.show()

#-----Applying CLAHE to L-channel-------------------------------------------
clahe = cv2.createCLAHE(clipLimit=5.0, tileGridSize=(8,8))
cl = clahe.apply(l)
plt.imshow(cl)
plt.show()

#-----Merge the CLAHE enhanced L-channel with the a and b channel-----------
limg = cv2.merge((cl,a,b))
plt.imshow(limg)
plt.show()

#-----Converting image from LAB Color model to RGB model--------------------
final = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)
plt.imshow(final)
plt.show()


###
#img1gnb = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
#img1g = cv2.GaussianBlur(img1gnb, (15,15), 5, 5)
val = np.ceil(np.mean(l) - np.std(l))
ret,imgthresh1 = cv2.threshold(l,val,255,cv2.THRESH_BINARY)
mask1 = imgthresh1 == 255
imgcl_clean = np.copy(l)
imgcl_clean[mask1] = 255
imgcl_clean = cv2.medianBlur(imgcl_clean, 9)

#img2gnb = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
#img2g = cv2.GaussianBlur(img2gnb, (15,15), 5, 5)
val = np.ceil(np.mean(a) + np.std(a))
ret,imgthresh2 = cv2.threshold(a,val,255,cv2.THRESH_BINARY_INV)
maska = imgthresh2 == 255
img1_clean = np.copy(a)
img1_clean[maska] = 0
img1m_clean = cv2.medianBlur(img1_clean, 9)

#img3gnb = cv2.cvtColor(img3, cv2.COLOR_BGR2GRAY)
#img3g = cv2.GaussianBlur(img3gnb, (15,15), 5, 5)
val = np.ceil(np.mean(b) - np.std(b))
ret,imgthresh3 = cv2.threshold(b,val,255,cv2.THRESH_BINARY)
mask3 = imgthresh3 == 255
imgb_clean = np.copy(b)
imgb_clean[mask3] = 255
imgb_clean = cv2.medianBlur(imgb_clean, 9)

