# -*- coding: utf-8 -*-
"""FeatExtract_Segment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Fw4gvJ_elGPbG4sZnxoYqUlGPoNf_Xbt
"""

from google.colab import drive
drive.mount('/content/gdrive')

import numpy as np
import cv2 
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import scipy
import os
os.chdir('/content/gdrive/My Drive/MP2/')

#Read Images
img = cv2.imread('benign_4x/_11064.tif')
img_gt = cv2.imread('benign_4x/_11064_gt.png')
img_gt = np.array(img_gt)

#Show original and ground truth image
fig, (a1,a2) = plt.subplots(1,2, figsize=(25,25))
a1.imshow(img)
a2.imshow(img_gt)
fig.show

#Extract Gabor Features

ksize = 9  # Size of Gabor kernel
theta = 0.0 
gamma = 1

#converting to grayscale
img_gray= cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
kernels = []
features = []

for sigma in np.arange(1,1.5,0.5):
  for lamda in np.arange(3,5,0.25):
    for gamma in np.arange(0.5,1.5,0.25):
      k = cv2.getGaborKernel((ksize, ksize), sigma, theta, lamda, gamma, 0, ktype=cv2.CV_32F)   
      kernels.append(k) 
      fimg = cv2.filter2D(imgHSV, cv2.CV_8UC1, k)
      #fimg = cv2.GaussianBlur(fimg, (15,15), 5, 5)
      fimg = cv2.medianBlur(fimg, 11)
      #plt.imshow(fimg)
      #plt.show()
      #fimg = fimg.reshape((fimg.shape[0]*fimg.shape[1],))
      #features.append(fimg)
      #ColourImage
      #fimg = cv2.filter2D(imgHSV[:,:,2], cv2.CV_8UC1, k)
      #fimg = cv2.GaussianBlur(fimg, (15,15), 5, 5)
      #fimg = cv2.medianBlur(fimg, 11)
      plt.imshow(fimg)
      plt.show()
      print(sigma, lamda, gamma)
      fimg = fimg.reshape((fimg.shape[0]*fimg.shape[1],3))
      features.append(fimg[:,0])
      features.append(fimg[:,1])
      features.append(fimg[:,2])

imgHSV = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
fig, (a1,a2, a3) = plt.subplots(1,3, figsize=(25,25))
a1.imshow(imgHSV[:,:,0], cmap = 'gray')
a2.imshow(imgHSV[:,:,1], cmap = 'gray')
a3.imshow(imgHSV[:,:,2], cmap = 'gray')
fig.show

features = []
features.append(imgHSV[:,:,0].reshape((img.shape[0]*img.shape[1]),))
features.append(imgHSV[:,:,1].reshape((img.shape[0]*img.shape[1]),))
features.append(imgHSV[:,:,2].reshape((img.shape[0]*img.shape[1]),))

imgHSV[:,:,1] = np.zeros(imgHSV[:,:,1].shape)
plt.figure(figsize = (15,15))
plt.imshow(imgHSV, cmap = 'gray')
plt.show()

features = np.array(features)
features = features.T
kernels = np.array(kernels)

#K Means Clustering
kmeans = KMeans(n_clusters=3)
kmeans.fit(features)
y = kmeans.predict(features)
img_seg = y.reshape((img.shape[0], img.shape[1]))
img_seg_copy = np.copy(img_seg)

#Plotting Segmented Image
fig, (a1,a2,a3) = plt.subplots(1,3, figsize=(25,25))
a1.imshow(img)
a2.imshow(img_gt)
a3.imshow(img_seg)
fig.show

img_seg_copy2 = np.copy(img_seg_copy)
unstained = np.uint(img_seg_copy2 == 2)
img_seg = unstained

#Find Contours
contours, heirarchy = cv2.findContours(np.uint8(img_seg), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

#Finding top n contours with maximum areas
n = 2
areas = []

for cnt in contours:
  area = cv2.contourArea(cnt)
  areas.append(area)

areas = np.array(areas)
ind = np.argsort(-1*areas)
max1 = contours[ind[0]]
max2 = contours[ind[1]]

z = np.zeros(img_seg.shape)

for i in np.arange(0,n,1):
  cv2.drawContours(z,contours[ind[i]], -1,(255,255,255), 3 )

plt.imshow(z, cmap = 'gray')
plt.show()

masked_image = scipy.ndimage.morphology.binary_fill_holes(z)
plt.imshow(masked_image, cmap = 'gray')
plt.show()

#Labelling the image

(labels, counts) = np.unique(img_seg[masked_image], return_counts= True)
cellClusterLabel = labels[np.argmax(counts)]
print(cellClusterLabel)
masked_img_inv = masked_image == False
backgroundMask = (img_seg == 0)
isolatedMask = ((img_seg *masked_img_inv) == 2).astype(int)
isolatedMask[masked_image] = 2

isolatedMask[backgroundMask] = 0

img_gt_gray = cv2.cvtColor(img_gt, cv2.COLOR_BGR2GRAY)

#Plotting correctly labelled Segmented Image
fig, (a1,a2,a3) = plt.subplots(1,3, figsize=(25,25))
a1.imshow(img)
a2.imshow(img_gt_gray, cmap = 'gray')
a3.imshow(isolatedMask, cmap = 'gray')
fig.show

#Calculate dice score 

dice = []
for k in (0,1,2):
  dice.append(np.sum(isolatedMask[img_gt==k])*2.0 / (np.sum(isolatedMask) + np.sum(img_gt)))

print(dice)

#Benign - 4x - 011
#img11 = np.copy(img)
#img_gt_gray11 = np.copy(img_gt_gray)
#isolatedMask11 = np.copy(isolatedMask)
#img_seg11 = np.copy(img_seg)
img11 = cv2.imread('benign_4x/_11001.tif')
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img11)
a2.imshow(img_gt_gray11, cmap = 'gray')
a3.imshow(isolatedMask11, cmap = 'gray')
a4.imshow(img_seg11)
fig.show
fig.savefig('b_011.png')

#Benign - 4x - 016
#img16 = np.copy(img)
#img_gt_gray16 = np.copy(img_gt_gray)
#isolatedMask16 = np.copy(isolatedMask)
#img_seg16 = np.copy(img_seg)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img16)
a2.imshow(img_gt_gray16, cmap = 'gray')
a3.imshow(isolatedMask16, cmap = 'gray')
a4.imshow(img_seg16)
fig.show
fig.savefig('b_016.png')

#Benign - 4x - 064
#img64 = np.copy(img)
#img_gt_gray64 = np.copy(img_gt_gray)
#isolatedMask64 = np.copy(isolatedMask)
#img_seg64 = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img64)
a2.imshow(img_gt_gray64, cmap = 'gray')
a3.imshow(isolatedMask64, cmap = 'gray')
a4.imshow(img_seg64)
fig.show
fig.savefig('b_064.png')

#Malignant - 4x - 017
img17m = np.copy(img)
img_gt_gray17m = np.copy(img_gt_gray)
isolatedMask17m = np.copy(isolatedMask)
img_seg17m = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img17m)
a2.imshow(img_gt_gray17m, cmap = 'gray')
a3.imshow(isolatedMask17m, cmap = 'gray')
a4.imshow(img_seg17m)
fig.show
fig.savefig('m_017.png')

#Malignant - 4x - 018
img18m = np.copy(img)
img_gt_gray18m = np.copy(img_gt_gray)
isolatedMask18m = np.copy(isolatedMask)
img_seg18m = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img18m)
a2.imshow(img_gt_gray18m, cmap = 'gray')
a3.imshow(isolatedMask18m, cmap = 'gray')
a4.imshow(img_seg18m)
fig.show
fig.savefig('m_018.png')

#Malignant - 4x - 020
img20m = np.copy(img)
img_gt_gray20m = np.copy(img_gt_gray)
isolatedMask20m = np.copy(isolatedMask)
img_seg20m = np.copy(img_seg_copy)
fig, (a1,a2,a3, a4) = plt.subplots(1,4, figsize=(25,25))
a1.imshow(img20m)
a2.imshow(img_gt_gray20m, cmap = 'gray')
a3.imshow(isolatedMask20m, cmap = 'gray')
a4.imshow(img_seg20m)
fig.show
fig.savefig('m_020.png')

